#
# qmake configuration for the Freescale iMX6 boards (single, dual and quad)
#
# This mkspec is based and tested on the
# This mkspec is tested with a framebuffer (eglfs)
# A typical configure line looks like:
# <path-to-qt-src>/configure -commercial -confirm-license -device vxworks-imx6 \
# -device-option CROSS_COMPILE=arm -sysroot <full_path_to_fsl_imx6_VSB_DIR> -no-gcc-sysroot \
# -prefix /sd0:1/qt5 -hostprefix /home/VxWorks7/qt5 -extprefix /home/VxWorks7/qt5
#

include(../common/vxworks_device_pre.conf)

EGLFS_PLATFORM_HOOKS_SOURCES = $$PWD/qeglfshooks_imx6.cpp

DEFINES                += _FSLVIV

QMAKE_LIBS_EGL          = -lgfxFslVivEGL -lgfxFslVivGLESv2 -lgfxFslVivGLSLC -lgfxFslVivGAL
QMAKE_LIBS_OPENGL_ES2   = -lgfxFslVivGLESv2 -lgfxFslVivEGL -lgfxFslVivGAL -lgfxFslVivGLSLC

IMX6_COMMON_FLAGS       = -t7 -mfpu=vfp -mfloat-abi=softfp
IMX6_CFLAGS             = $$IMX6_COMMON_FLAGS -D_VX_CPU=_VX_ARMARCH7 -D_VX_TOOL=gnu -DARMEL
IMX6_CFLAGS_RELEASE     = $$IMX6_CFLAGS
QMAKE_CFLAGS_RELEASE   += $$IMX6_CFLAGS_RELEASE
QMAKE_CXXFLAGS_RELEASE += $$IMX6_CFLAGS_RELEASE
QMAKE_CFLAGS_DEBUG     += $$IMX6_CFLAGS
QMAKE_CXXFLAGS_DEBUG   += $$IMX6_CFLAGS
QMAKE_CFLAGS_RELEASE_WITH_DEBUGINFO += $$IMX6_CFLAGS_RELEASE
QMAKE_CXXFLAGS_RELEASE_WITH_DEBUGINFO += $$IMX6_CFLAGS_RELEASE

QMAKE_LFLAGS_APP       += -Wl,-T$(WIND_BASE)/build/tool/gnu_4_8_1/usr/ldscript.vxe.arm
QMAKE_LFLAGS_SHLIB     += $$IMX6_COMMON_FLAGS

load(qt_config)
