#
# qmake configuration for the Freescale iMX6 boards (single, dual and quad)
#
# This mkspec is based and tested on the
# This mkspec is tested with a framebuffer (eglfs)
# A typical configure line looks like:
# <path-to-qt-src>/configure -commercial -confirm-license -device vxworks-imx6-clang \
# -sysroot <full_path_to_fsl_imx6_VSB_DIR> -no-gcc-sysroot -no-openssl \
# -prefix /sd0:1/qt5 -hostprefix /home/VxWorks7/qt5 -extprefix /home/VxWorks7/qt5
#

# Target architecture dependent way to specify the base address of the absolutely linked
# RTP executables
VX_RTP_LINK_ADDR = 0x80000000

include(../common/vxworks_device_pre.conf)

# Preferred eglfs backend
EGLFS_DEVICE_INTEGRATION = eglfs_viv

DEFINES                 += _FSLVIV

QMAKE_LIBS_EGL          = -lgfxFslVivEGL -lgfxFslVivGLESv2 -lgfxFslVivGLSLC -lgfxFslVivGAL
QMAKE_LIBS_OPENGL_ES2   = -lgfxFslVivGLESv2 -lgfxFslVivEGL -lgfxFslVivGAL -lgfxFslVivGLSLC

QMAKE_LIBDIR_OPENGL_ES2 += $$[QT_SYSROOT]/usr/lib/common
QMAKE_INCDIR_OPENGL_ES2 += $$[QT_SYSROOT]/usr/h/public

QMAKE_LIBDIR_EGL        += $$[QT_SYSROOT]/usr/lib/common
QMAKE_INCDIR_EGL        += $$[QT_SYSROOT]/usr/h/public

equals(VXWORKS_BUILD_LIBRARY_TYPE, "static") {
    QMAKE_LIBS_EGL = --start-group -l:libgfxFslVivEGL.a -l:libgfxFslVivGLESv2.a -l:libgfxFslVivGLSLC.a -l:libgfxFslVivGAL.a --end-group
    QMAKE_LIBS_OPENGL_ES2 = --start-group -l:libgfxFslVivGLESv2.a -l:libgfxFslVivEGL.a -l:libgfxFslVivGAL.a -l:libgfxFslVivGLSLC.a --end-group
}

equals(VXWORKS_BUILD_LIBRARY_TYPE, "shared") {
    QMAKE_LFLAGS_APP    += --target2=got-rel
    QMAKE_LFLAGS_SHLIB  += --target2=got-rel
}

DEFINES               += GL_GLEXT_PROTOTYPES

IMX6_COMMON_FLAGS       = --target=arm-eabi -march=armv7-a -mcpu=cortex-a9 -mfloat-abi=hard -mfpu=vfpv3
IMX6_CFLAGS             = $$IMX6_COMMON_FLAGS -MD -MP -D_VX_CPU=_VX_ARMARCH7 -D_VX_TOOL_FAMILY=llvm -D_VX_TOOL=llvm -D_VSB_CONFIG_FILE=\'<$$[QT_SYSROOT]/h/config/vsbConfig.h>\' -DARMEL
IMX6_LFLAGS             = -EL

IMX6_CFLAGS_RELEASE     = $$IMX6_CFLAGS
QMAKE_CFLAGS_RELEASE   += $$IMX6_CFLAGS_RELEASE
QMAKE_CXXFLAGS_RELEASE += $$IMX6_CFLAGS_RELEASE
QMAKE_CFLAGS_DEBUG     += $$IMX6_CFLAGS
QMAKE_CXXFLAGS_DEBUG   += $$IMX6_CFLAGS
QMAKE_CFLAGS_RELEASE_WITH_DEBUGINFO += $$IMX6_CFLAGS_RELEASE
QMAKE_CXXFLAGS_RELEASE_WITH_DEBUGINFO += $$IMX6_CFLAGS_RELEASE
QMAKE_LFLAGS           += $$IMX6_LFLAGS

load(qt_config)
