#
# Qmake configuration for Clang on VxWorks
#
include(../clang.conf)

DEFINES                 += QT_NO_SYSTEMLOCALE

QMAKE_COMPILER          += vxworks_clang

QMAKE_CC                = clang
QMAKE_CXX               = clang++

QMAKE_AR                = ararm crus
QMAKE_LINK              = ldarm
QMAKE_LINK_SHLIB        = $$QMAKE_LINK

QMAKE_INCDIR            = $$[QT_SYSROOT]/share/h
QMAKE_LIBDIR            = $$[QT_SYSROOT]/usr/lib/common

# Always needed...
QMAKE_LIBS_NETWORK    += -lnet

QMAKE_CFLAGS_RELEASE_WITH_DEBUGINFO += -gdwarf-3
QMAKE_CXXFLAGS_RELEASE_WITH_DEBUGINFO += -gdwarf-3

COMMON_INC_FLAGS    = -isystem$$[QT_SYSROOT]/usr/h/published/UTILS_UNIX -isystem$$[QT_SYSROOT]/usr/h -isystem$$[QT_SYSROOT]/usr/h/public -isystem$$[QT_SYSROOT]/usr/h/public/tool/llvm
COMMON_CFLAGS       = -fno-strict-aliasing -fno-builtin -D__vxworks -D__VXWORKS__ -D__RTP__ -D__ELF__ -nostdlibinc -nostdinc++ -fasm -Wall -D_USE_INIT_ARRAY $$COMMON_INC_FLAGS
COMMON_LFLAGS       = -u __wr_need_frame_add -u __tls__ -T$$[QT_SYSROOT]/usr/ldscripts/rtp.ld

QMAKE_CFLAGS        = $$COMMON_CFLAGS
QMAKE_CXXFLAGS      = $$COMMON_CFLAGS

QMAKE_LFLAGS_APP            = --defsym __wrs_rtp_base=$$VX_RTP_LINK_ADDR $$[QT_SYSROOT]/usr/lib/common/crt0.o $$COMMON_LFLAGS
QMAKE_CFLAGS_SHLIB          = -fpic
QMAKE_CFLAGS_PLUGIN         = $$QMAKE_CFLAGS_SHLIB
QMAKE_CFLAGS_STATIC_LIB     = $$QMAKE_CFLAGS_SHLIB
QMAKE_CXXFLAGS_STATIC_LIB   = $$QMAKE_CFLAGS_SHLIB


QMAKE_CFLAGS_SHLIB         += $$QMAKE_CFLAGS_PIC
QMAKE_CFLAGS_STATIC_LIB    += $$QMAKE_CFLAGS_PIC
QMAKE_CFLAGS_APP           += $$QMAKE_CFLAGS_PIC

QMAKE_LFLAGS_VERSION_SCRIPT = --version-script$${LITERAL_WHITESPACE}

QMAKE_LFLAGS_SONAME         = -soname=
QMAKE_LFLAGS_RPATH          = -rpath$${LITERAL_WHITESPACE}
QMAKE_LFLAGS_RPATHLINK      = -rpath-link$${LITERAL_WHITESPACE}
QMAKE_RPATHLINKDIR_POST     = $$[QT_SYSROOT]/usr/lib/common

QMAKE_LFLAGS_GCSECTIONS     = --gc-sections

# shared library specific flags
equals(VXWORKS_BUILD_LIBRARY_TYPE, "shared") {
    QMAKE_LIBS                = -lllvmcplus -lllvm -lcplusplus -lunix -lc -lc_internal_s -lz
    QMAKE_LIBS                += -L$$[QT_SYSROOT]/usr/lib/common/PIC
    QMAKE_LFLAGS_APP          += -L$$[QT_SYSROOT]/usr/lib/common  --as-needed --start-group -ldl -lllvmcplus -lllvm -lcplusplus -lunix -lz -lc --end-group
    QMAKE_LFLAGS_SHLIB        += --as-needed --exclude-libs libc_internal_s.a -u __init -u __fini $$COMMON_LFLAGS
    QMAKE_CFLAGS_SHLIB        += $$QMAKE_CFLAGS -D__SO_PICABILINUX__
    QMAKE_CXXFLAGS_SHLIB      += $$QMAKE_CFLAGS_SHLIB
    QMAKE_LFLAGS_PLUGIN       += $$QMAKE_LFLAGS_SHLIB
    QMAKE_CFLAGS_STATIC_LIB   += $$QMAKE_CFLAGS_SHLIB
    QMAKE_CXXFLAGS_STATIC_LIB += $$QMAKE_CFLAGS_STATIC_LIB
}

# shared library specific flags
equals(VXWORKS_BUILD_LIBRARY_TYPE, "static") {
    QMAKE_LFLAGS_APP          += -static -L$$[QT_SYSROOT]/usr/lib/common
    QMAKE_LIBS                = --start-group -lc -lc_internal -lllvm -lcplusplus -lllvmcplus -lunix --end-group -lz
}
