include(../../common/g++-unix.conf)

DEFINES                 += QT_NO_SYSTEMLOCALE

# modifications to g++-unix.conf
QMAKE_CC                = cc$${CROSS_COMPILE}
QMAKE_CXX               = c++$${CROSS_COMPILE}
QMAKE_LINK              = $${QMAKE_CXX}
QMAKE_LINK_SHLIB        = $${QMAKE_CXX}

# modifications to linux.conf
QMAKE_AR                = ar$${CROSS_COMPILE} crus
QMAKE_OBJCOPY           = objcopy$${CROSS_COMPILE}
QMAKE_NM                = nm$${CROSS_COMPILE} -P
QMAKE_STRIP             = strip$${CROSS_COMPILE}
QMAKE_STRIPFLAGS_LIB   += --strip-unneeded

# additions
QMAKE_LIBS              =
QMAKE_LIBS_DYNLOAD      =
QMAKE_LIBS_THREAD       =

QMAKE_CFLAGS_THREAD    += -D_REENTRANT
QMAKE_CXXFLAGS_THREAD  += $$QMAKE_CFLAGS_THREAD
QMAKE_LFLAGS_GCSECTIONS = -Wl,--gc-sections

QMAKE_INSTALL_FILE      = install -m 644 -p
QMAKE_INSTALL_PROGRAM   = install -m 755 -p

QMAKE_INCDIR            = $$[QT_SYSROOT]/share/h $$[QT_SYSROOT]/usr/h $$[QT_SYSROOT]/usr/h/public
QMAKE_LIBDIR            = $$[QT_SYSROOT]/usr/lib/common
QMAKE_RPATHLINKDIR_POST = $$[QT_SYSROOT]/usr/lib/common

# common flags for compiler and linker
VX_COMMON_FLAGS           = -mrtp -fasm -Wall
VX_COMMON_COMPILER_FLAGS  = $$VX_COMMON_FLAGS -D_VX_TOOL_FAMILY=gnu -D_VX_TOOL=gnu
VX_COMMON_COMPILER_FLAGS += -D_VSB_CONFIG_FILE=\'<$$[QT_SYSROOT]/h/config/vsbConfig.h>\'

VX_COMMON_LINKER_FLAGS    = $$VX_COMMON_FLAGS -Wl,--defsym,__wrs_rtp_base=0x80000000 -Wl,-u,__tls__

QMAKE_CFLAGS            = $$VX_COMMON_COMPILER_FLAGS -L$$[QT_SYSROOT]/usr/lib/common
QMAKE_CXXFLAGS          = $$QMAKE_CFLAGS

# Needed for C++11 support
QMAKE_CXXFLAGS         += $$QMAKE_CXXFLAGS_CXX11 -isystem$$[QT_SYSROOT]/usr/h/public/c++11 -isystem$$[QT_SYSROOT]/usr/h -D_C99 -D_HAS_C9X -D_IS_WRS -isystem$$[QT_SYSROOT]/usr/h/public
QMAKE_LIBS_PRIVATE      = -lsupc++ -lstdc++11

QMAKE_CFLAGS_DEPS       = -MD -MP
QMAKE_CXXFLAGS_DEPS     = $$QMAKE_CFLAGS_DEPS

QMAKE_CFLAGS_RELEASE   += -fstrength-reduce -fno-builtin
QMAKE_CFLAGS_RELEASE_WITH_DEBUGINFO += $$QMAKE_CFLAGS_RELEASE

QMAKE_CXXFLAGS_RELEASE += $$QMAKE_CFLAGS_RELEASE
QMAKE_CXXFLAGS_RELEASE_WITH_DEBUGINFO += $$QMAKE_CFLAGS_RELEASE_WITH_DEBUGINFO

QMAKE_CFLAGS_SHLIB      =
QMAKE_CXXFLAGS_SHLIB    = $$QMAKE_CFLAGS_SHLIB
QMAKE_CFLAGS_STATIC_LIB =
QMAKE_CXXFLAGS_STATIC_LIB = $$QMAKE_CFLAGS_STATIC_LIB
QMAKE_CFLAGS_APP        =
QMAKE_CXXFLAGS_APP      = $$QMAKE_CFLAGS_APP

QMAKE_CFLAGS_EXCEPTIONS_OFF   =
QMAKE_CXXFLAGS_EXCEPTIONS_OFF = $$QMAKE_CFLAGS_EXCEPTIONS_OFF

QMAKE_LFLAGS_APP        = $$VX_COMMON_LINKER_FLAGS
QMAKE_LFLAGS_SHLIB      = $$VX_COMMON_FLAGS
QMAKE_LFLAGS_PLUGIN     = $$QMAKE_LFLAGS_SHLIB
QMAKE_LFLAGS_NOUNDEF    =

# shared library specific flags
equals(VXWORKS_BUILD_LIBRARY_TYPE, "shared") {
    QMAKE_LFLAGS_APP         += -non-static
    QMAKE_LFLAGS_SHLIB       += -fpic -D__SO_PICABILINUX__ -shared -L$$[QT_SYSROOT]/usr/lib/common/PIC
    QMAKE_CFLAGS_SHLIB        = -fpic -D__SO_PICABILINUX__
    QMAKE_CXXFLAGS_SHLIB      = $$QMAKE_CFLAGS_SHLIB
    QMAKE_LFLAGS_PLUGIN       = $$QMAKE_LFLAGS_SHLIB
    QMAKE_CFLAGS_STATIC_LIB   = $$QMAKE_CFLAGS_SHLIB
    QMAKE_CXXFLAGS_STATIC_LIB = $$QMAKE_CFLAGS_STATIC_LIB
}
