QT_QPA_DEFAULT_PLATFORM = eglfs

MAKEFILE_GENERATOR      = UNIX
CONFIG                 += incremental
QMAKE_INCREMENTAL_STYLE = sublib
QMAKE_PLATFORM         += vxworks

include(../../common/unix.conf)
include(../../common/gcc-base-unix.conf)

contains(QMAKE_HOST.os,Windows) {
    include(../../common/vxworks/windows.conf)
}

!load(device_config) {
    error(Could not successfully load device configuration)
}

# Check if required env variables are set
!exists($$(WIND_BASE)): error("You need to set WIND_BASE environment variable to point to VxWorks7 directory.")

equals(VXWORKS_BUILD_TOOL, "clang") {
    include(../../common/vxworks/clang.conf)
} else {
    include(../../common/vxworks/g++.conf)
}
